package com.rmap.mobile.core.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF298CF7)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF3875B7)
val OnPrimaryContainerLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF4F8FF)
val OnBackgroundLight = Color(0xFF111827)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF111827)
val CardBorderColor = Color(0x80F9FAFB)
val CardShadowColor = Color(0x0F000000)
val CardDividerColor = Color(0xFFF3F4F6)
val CardDividerStrongColor = Color(0xCCF3F4F6)
val CardShadowSubtleColor = Color(0x0A000000)
val CardShadowSoftColor = Color(0x08000000)
val CardShadowOverlayColor = Color(0x1A000000)
val CardPrimaryBorderColor = Color(0x1A298CF7)
val CardPrimaryGlowColor = Color(0xCCF4F8FF)
val CardPrimaryGlowStrongColor = Color(0x4D298CF7)
val CardPrimaryGlowMediumColor = Color(0x26298CF7)
val CardPrimaryGlowSoftColor = Color(0x14298CF7)
val CardPrimaryGlowSubtleColor = Color(0x10298CF7)
val CardPrimaryGlowFaintColor = Color(0x0A298CF7)
val CardPrimaryGlowBareColor = Color(0x0D298CF7)
val PrimaryBlueOverlaySoftColor = Color(0x26007AFF)
val PrimaryBlueOverlayFaintColor = Color(0x0D007AFF)
val PrimaryBlueShadowColor = Color(0x40007AFF)
val PrimaryHeroShadowColor = Color(0x66006FFF)
val PrimaryAvatarShadowColor = Color(0x33298CF7)

val NeutralBorderColor = Color(0xFFE5E7EB)
val NeutralDividerDotColor = Color(0xFFD1D5DB)
val NeutralTextMutedColor = Color(0xFF6B7280)
val NeutralTextBodyColor = Color(0xFF4B5563)
val NeutralDisabledColor = Color(0xFF9CA3AF)
val NeutralDisabledTextColor = Color(0xFF6A7282)
val NeutralSoftSurfaceColor = Color(0xFFF3F4F6)
val Neutral900Color = Color(0xFF111827)
val ProfileIconContainerColor = Color(0xFFF4F3F7)
val HeadingTextColor = Color(0xFF2D3142)

val DifficultyExpertContainerColor = Color(0xFFF3E8FF)
val DifficultyExpertContentColor = Color(0xFF9810FA)
val DifficultyBeginnerContainerColor = Color(0xFFD0FBDC)
val DifficultyIntermediateContainerColor = Color(0xFFDBEAFA)
val DifficultyHardContainerColor = Color(0xFFFFEDD4)
val StatusSuccessContainerColor = Color(0xFFECFDF5)
val StatusSuccessContentColor = Color(0xFF10B981)
val StatusCompletedContentColor = Color(0xFF0F8330)
val StatusWarningContainerColor = Color(0xFFFFFBEB)
val StatusWarningContentColor = Color(0xFFF59E0B)
val StatusDangerContainerColor = Color(0xFFFEF2F2)
val StatusDangerContentColor = Color(0xFFFB2C36)
val StatusHardContentColor = Color(0xFFF54900)
val InfoContainerColor = Color(0xFFEFF6FF)
val ExploreBlueContainerColor = Color(0xFFEBF5FF)
val ExploreRoseContainerColor = Color(0xFFFFF1F2)
val ExploreGreenContainerColor = Color(0xFFF0FDF4)
val ExplorePurpleContainerColor = Color(0xFFF5F3FF)

val AccentPurpleColor = Color(0xFF7B61FF)
val AccentCyanColor = Color(0xFF00D3F3)
val AccentBlueColor = Color(0xFF007AFF)
val AccentPurpleGlowColor = Color(0xFFC27AFF)
val AiTipContainerEndColor = Color(0xFFEAF2FF)
val CoverSurfaceColor = Color(0xFF0F172B)
val CoverPreviewSurfaceColor = Color(0xFF1E3A5F)

val PrimaryDark = Color(0xFF90CAF9)
val OnPrimaryDark = Color(0xFF003258)
val PrimaryContainerDark = Color(0xFF0D47A1)
val OnPrimaryContainerDark = Color(0xFFD6E4FF)
val BackgroundDark = Color(0xFF0B1220)
val OnBackgroundDark = Color(0xFFE5E7EB)
val SurfaceDark = Color(0xFF111827)
val OnSurfaceDark = Color(0xFFE5E7EB)
